# 50 Numpy Functions

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3]) 
print (a)

[1 2 3]


In [4]:
np.array([1, 2, 3,4,5], ndmin = 2) 

array([[1, 2, 3, 4, 5]])

In [5]:
np.array([1, 2, 3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)

(2, 3)


In [7]:
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
a = np.arange(24) 
a.ndim  

1

In [10]:
b = a.reshape(2,4,3) 
print (b) 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [11]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


In [12]:
x = np.array([1,2,3,4,5], dtype = np.float32) 
print (x.itemsize)

4


In [13]:
x = np.array([1,2,3,4,5]) 
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [14]:
x = np.empty([3,2], dtype = int) 
print (x)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
x = np.zeros(5) 
print (x)

[0. 0. 0. 0. 0.]


In [16]:
x = np.ones([2,2], dtype = int) 
print (x)

[[1 1]
 [1 1]]


In [17]:
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)

[(1, 2, 3) (4, 5)]


C:\Users\HAMZA\anaconda3\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [20]:
list = range(5)

x = np.fromiter(list, dtype = float) 
print (x)

[0. 1. 2. 3. 4.]


In [2]:
import numpy as np 
x = np.linspace(10,20,5) 
print (x)

[10.  12.5 15.  17.5 20. ]


In [3]:
a = np.logspace(1.0, 2.0, num = 10) 
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [4]:
a = np.arange(10) 
s = slice(2,7,2) 
a[s]

array([2, 4, 6])

In [5]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
a  

a[1:]

array([[3, 4, 5],
       [4, 5, 6]])

In [7]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)
print (a[...,1] )
print ('\n' ) 
print (a[1,...] )
print ('\n'  )
print (a[...,1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[2 4 5]


[3 4 5]


[[2 3]
 [4 5]
 [5 6]]
